openapi: 3.0.1
info:
  description: "Add, manage, and remove users from your account"
  title: User Provisioning
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-api-use-case: "You manage employee access data in a system outside of\
    \ HubSpot, and you want to ensure that specific users are dynamically allocated\
    \ to the right teams in your HubSpot account."
  x-hubspot-related-documentation:
  - name: User Provisioning Guide
    url: https://developers.hubspot.com/docs/guides/api/settings/users/user-provisioning
  x-hubspot-introduction: "Use the user provisioning API to create and manage users\
    \ in your HubSpot account, along with their associated teams and roles."
servers:
- url: https://api.hubapi.com
tags:
- name: Teams
- name: Roles
- name: Users
paths:
  /settings/v3/users/teams:
    get:
      description: View teams for this account
      operationId: get-/settings/v3/users/teams_getAll
      security:
      - private_apps:
        - settings.users.teams.read
      - oauth2:
        - settings.users.teams.read
      summary: See details about this account's teams
      tags:
      - Teams
  /settings/v3/users/roles:
    get:
      description: Retrieves the roles on an account
      operationId: get-/settings/v3/users/roles_getAll
      security:
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - settings.users.read
      - oauth2:
        - crm.objects.users.read
      - private_apps:
        - settings.users.read
      summary: Retrieves the roles on an account
      tags:
      - Roles
  /settings/v3/users/:
    get:
      description: Retrieves a list of users from an account
      operationId: get-/settings/v3/users/_getPage
      security:
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - settings.users.read
      - oauth2:
        - crm.objects.users.read
      - private_apps:
        - settings.users.read
      summary: Retrieves a list of users from an account
      tags:
      - Users
    post:
      description: "New users will only have minimal permissions, which is contacts-base.\
        \ A welcome email will prompt them to set a password and log in to HubSpot."
      operationId: post-/settings/v3/users/_create
      security:
      - private_apps:
        - settings.users.write
      - oauth2:
        - settings.users.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.users.write
      summary: Adds a user
      tags:
      - Users
  /settings/v3/users/{userId}:
    delete:
      description: "Removes a user identified by `userId`. `userId` refers to the\
        \ user's ID by default, or optionally email as specified by the `IdProperty`\
        \ query param."
      operationId: "delete-/settings/v3/users/{userId}_archive"
      security:
      - private_apps:
        - settings.users.write
      - oauth2:
        - settings.users.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.users.write
      summary: Removes a user
      tags:
      - Users
    get:
      description: "Retrieves a user identified by `userId`. `userId` refers to the\
        \ user's ID by default, or optionally email as specified by the `IdProperty`\
        \ query param."
      operationId: "get-/settings/v3/users/{userId}_getById"
      security:
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - settings.users.read
      - oauth2:
        - crm.objects.users.read
      - private_apps:
        - settings.users.read
      summary: Retrieves a user
      tags:
      - Users
    put:
      description: "Modifies a user identified by `userId`. `userId` refers to the\
        \ user's ID by default, or optionally email as specified by the `IdProperty`\
        \ query param."
      operationId: "put-/settings/v3/users/{userId}_replace"
      security:
      - private_apps:
        - settings.users.write
      - oauth2:
        - settings.users.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.users.write
      summary: Modifies a user
      tags:
      - Users
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            settings.users.read: View account data.
            crm.objects.users.read: Read User CRM objects
            settings.users.write: "Create, modify, and delete users on your account"
            crm.objects.users.write: Write User CRM objects
            settings.users.teams.read: View teams for this account.
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
