openapi: 3.0.1
info:
  description: ""
  title: Emails
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-api-use-case: "You send and manage emails to your customers using a third-party\
    \ email provider, and you want to programmatically log your email data to the\
    \ associated records in your HubSpot account."
  x-hubspot-related-documentation:
  - name: Emails Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/engagements/email
  x-hubspot-introduction: "Use the email engagements API to associate emails with\
    \ records in your CRM. You can include various metadata fields as needed, including\
    \ the email's headers, subject line, and body."
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Basic
- name: Search
paths:
  /crm/v3/objects/emails/batch/read:
    post:
      description: 'Retrieve records by record ID or include the `idProperty` parameter
        to retrieve records by a custom unique value property. '
      operationId: post-/crm/v3/objects/emails/batch/read_read
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: "Read a batch of emails by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/emails/{emailId}:
    delete:
      description: "Move an Object identified by `{emailId}` to the recycling bin."
      operationId: "delete-/crm/v3/objects/emails/{emailId}_archive"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Archive
      tags:
      - Basic
    get:
      description: "Read an Object identified by `{emailId}`. `{emailId}` refers to\
        \ the internal object ID by default, or optionally any unique property value\
        \ as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: "get-/crm/v3/objects/emails/{emailId}_getById"
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: Read
      tags:
      - Basic
    patch:
      description: "Perform a partial update of an Object identified by `{emailId}`or\
        \ optionally a unique property value as specified by the `idProperty` query\
        \ param. `{emailId}` refers to the internal object ID by default, and the\
        \ `idProperty` query param refers to a property whose values are unique for\
        \ the object. Provided property values will be overwritten. Read-only and\
        \ non-existent properties will result in an error. Properties values can be\
        \ cleared by passing an empty string."
      operationId: "patch-/crm/v3/objects/emails/{emailId}_update"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Update
      tags:
      - Basic
  /crm/v3/objects/emails/batch/archive:
    post:
      operationId: post-/crm/v3/objects/emails/batch/archive_archive
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Archive a batch of emails by ID
      tags:
      - Batch
  /crm/v3/objects/emails/batch/create:
    post:
      operationId: post-/crm/v3/objects/emails/batch/create_create
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create a batch of emails
      tags:
      - Batch
  /crm/v3/objects/emails/batch/update:
    post:
      operationId: post-/crm/v3/objects/emails/batch/update_update
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: "Update a batch of emails by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/emails:
    get:
      description: Read a page of emails. Control what is returned via the `properties`
        query param.
      operationId: get-/crm/v3/objects/emails_getPage
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: List
      tags:
      - Basic
    post:
      description: "Create a email with the given properties and return a copy of\
        \ the object, including the ID. Documentation and examples for creating standard\
        \ emails is provided."
      operationId: post-/crm/v3/objects/emails_create
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create
      tags:
      - Basic
  /crm/v3/objects/emails/batch/upsert:
    post:
      description: Create or update records identified by a unique property value
        as specified by the `idProperty` query param. `idProperty` query param refers
        to a property whose values are unique for the object.
      operationId: post-/crm/v3/objects/emails/batch/upsert_upsert
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create or update a batch of emails by unique property values
      tags:
      - Batch
  /crm/v3/objects/emails/search:
    post:
      operationId: post-/crm/v3/objects/emails/search_doSearch
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.users.write: Write User CRM objects
            crm.objects.services.write: Write services
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.custom.write: Change custom object records
            crm.objects.quotes.read: Quotes
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.custom.highly_sensitive.read.v2: View custom object records
              (highly-sensitive)
            crm.objects.goals.write: Write goals
            crm.objects.custom.sensitive.read.v2: View custom object records (sensitive)
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.appointments.sensitive.read.v2: Read appointments (sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.deals.write: ' '
            crm.objects.leads.write: Modify lead objects
            crm.objects.companies.read: ' '
            crm.objects.listings.read: Read listings
            crm.objects.deals.highly_sensitive.read.v2: View deal records (highly-sensitive)
            crm.objects.contacts.write: ' '
            crm.objects.carts.write: Write cart
            crm.objects.companies.sensitive.read.v2: ' '
            crm.objects.invoices.read: Read invoices objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.invoices.write: Write invoices
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            crm.objects.goals.read: Read goals
            crm.objects.custom.highly_sensitive.write.v2: Change custom object records
              (highly-sensitive)
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.appointments.write: Write appointments
            media_bridge.read: Read media and media events
            crm.objects.line_items.write: Line Items
            crm.objects.orders.read: Read Orders
            crm.objects.subscriptions.write: Write to Commerce Subscriptions
            crm.objects.contacts.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.quotes.write: Quotes
            crm.objects.deals.sensitive.read.v2: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.users.read: Read User CRM objects
            tickets: Read and write tickets
            crm.objects.companies.sensitive.write.v2: ' '
            crm.objects.leads.read: Read lead objects
            crm.objects.services.read: Read services
            crm.objects.courses.write: Write courses
            crm.objects.custom.read: View custom object records
            crm.objects.listings.write: Write listings
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.deals.read: ' '
            crm.objects.companies.highly_sensitive.read.v2: View company records (highly-sensitive)
            e-commerce: e-commerce
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.objects.appointments.read: Read appointments
            crm.objects.orders.write: Write orders
            crm.objects.custom.sensitive.write.v2: Change custom object records (sensitive)
            crm.objects.carts.read: Read carts
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
