openapi: 3.0.1
info:
  description: |-
    Pipelines represent distinct stages in a workflow, like closing a deal or servicing a support ticket. These endpoints provide access to read and modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object types.

    ## Pipeline ID validation

    When calling endpoints that take pipelineId as a parameter, that ID must correspond to an existing, un-archived pipeline. Otherwise the request will fail with a `404 Not Found` response.
  title: Pipelines
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: STARTER
  x-hubspot-api-use-case: "To streamline customer support processes, use this API\
    \ to retrieve your existing ticket pipelines and add new stages based on your\
    \ business needs. Support reps can then assign tickets to those pipeline stages\
    \ to track progress on customer issues."
  x-hubspot-related-documentation:
  - name: Pipelines Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/pipelines
  x-hubspot-introduction: "Use the pipelines API to create and manage deal and ticket\
    \ pipelines. Pipelines enable you to track the status or progress of deals and\
    \ tickets, such as closing deals and opening support tickets."
servers:
- url: https://api.hubapi.com
tags:
- name: Pipeline Stage Audits
- name: Pipelines
- name: Pipeline Audits
- name: Pipeline Stages
paths:
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit:
    get:
      description: "Return a reverse chronological list of all mutations that have\
        \ occurred on the pipeline stage identified by `{stageId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit_getAudit"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.schemas.appointments.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.schemas.orders.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Return an audit of all changes to the pipeline stage
      tags:
      - Pipeline Stage Audits
  /crm/v3/pipelines/{objectType}/{pipelineId}:
    delete:
      description: "Delete the pipeline identified by `{pipelineId}`."
      operationId: "delete-/crm/v3/pipelines/{objectType}/{pipelineId}_archive"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Delete a pipeline
      tags:
      - Pipelines
    get:
      description: "Return a single pipeline object identified by its unique `{pipelineId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}_getById"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.schemas.appointments.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.schemas.orders.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Return a pipeline by ID
      tags:
      - Pipelines
    patch:
      description: "Perform a partial update of the pipeline identified by `{pipelineId}`.\
        \ The updated pipeline will be returned in the response."
      operationId: "patch-/crm/v3/pipelines/{objectType}/{pipelineId}_update"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Update a pipeline
      tags:
      - Pipelines
    put:
      description: Replace all the properties of an existing pipeline with the values
        provided. This will overwrite any existing pipeline stages. The updated pipeline
        will be returned in the response.
      operationId: "put-/crm/v3/pipelines/{objectType}/{pipelineId}_replace"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Replace a pipeline
      tags:
      - Pipelines
  /crm/v3/pipelines/{objectType}/{pipelineId}/audit:
    get:
      description: "Return a reverse chronological list of all mutations that have\
        \ occurred on the pipeline identified by `{pipelineId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}/audit_getAudit"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.schemas.appointments.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.schemas.orders.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Return an audit of all changes to the pipeline
      tags:
      - Pipeline Audits
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages:
    get:
      description: "Return all the stages associated with the pipeline identified\
        \ by `{pipelineId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_getAll"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.schemas.appointments.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.schemas.orders.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Return all stages of a pipeline
      tags:
      - Pipeline Stages
    post:
      description: "Create a new stage associated with the pipeline identified by\
        \ `{pipelineId}`. The entire stage object, including its unique ID, will be\
        \ returned in the response."
      operationId: "post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_create"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a pipeline stage
      tags:
      - Pipeline Stages
  /crm/v3/pipelines/{objectType}:
    get:
      description: "Return all pipelines for the object type specified by `{objectType}`."
      operationId: "get-/crm/v3/pipelines/{objectType}_getAll"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.schemas.appointments.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.schemas.orders.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Retrieve all pipelines
      tags:
      - Pipelines
    post:
      description: "Create a new pipeline with the provided property values. The entire\
        \ pipeline object, including its unique ID, will be returned in the response."
      operationId: "post-/crm/v3/pipelines/{objectType}_create"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a pipeline
      tags:
      - Pipelines
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}:
    delete:
      description: "Delete the pipeline stage identified by `{stageId}` associated\
        \ with the pipeline identified by `{pipelineId}`."
      operationId: "delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_archive"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Delete a pipeline stage
      tags:
      - Pipeline Stages
    get:
      description: "Return the stage identified by `{stageId}` associated with the\
        \ pipeline identified by `{pipelineId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_getById"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.schemas.appointments.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.schemas.orders.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Return a pipeline stage by ID
      tags:
      - Pipeline Stages
    patch:
      description: "Perform a partial update of the pipeline stage identified by `{stageId}`\
        \ associated with the pipeline identified by `{pipelineId}`. Any properties\
        \ not included in this update will keep their existing values. The updated\
        \ stage will be returned in the response."
      operationId: "patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_update"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Update a pipeline stage
      tags:
      - Pipeline Stages
    put:
      description: Replace all the properties of an existing pipeline stage with the
        values provided. The updated stage will be returned in the response.
      operationId: "put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_replace"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Replace a pipeline stage
      tags:
      - Pipeline Stages
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.schemas.custom.read: View custom object definitions
            crm.schemas.deals.read: ' '
            crm.pipelines.orders.read: View details about your cart pipelines including
              pipeline stage information
            crm.objects.listings.read: Read listings
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.objects.owners.read: ' '
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
            crm.schemas.courses.read: Read courses property settings
            crm.objects.companies.highly_sensitive.read.v2: View company records (highly-sensitive)
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.schemas.services.read: Read services property settings
            crm.objects.carts.read: Read carts
            crm.objects.contacts.write: ' '
            crm.objects.leads.write: Modify lead objects
            crm.schemas.listings.read: Read listings property settings
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.custom.sensitive.write.v2: Change custom object records (sensitive)
            crm.objects.appointments.read: Read appointments
            crm.objects.goals.read: Read goals
            crm.schemas.carts.read: Read cart property settings
            crm.objects.services.write: Write services
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.contacts.read: ' '
            crm.objects.custom.sensitive.read.v2: View custom object records (sensitive)
            crm.objects.appointments.sensitive.read.v2: Read appointments (sensitive)
            crm.objects.leads.read: Read lead objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.appointments.write: Write appointments
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            crm.schemas.contacts.read: ' '
            automation: Read from and write to my Workflows
            crm.objects.courses.write: Write courses
            crm.objects.quotes.write: Quotes
            crm.objects.invoices.read: Read invoices objects
            crm.objects.feedback_submissions.read: View feedback survey submissions
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.schemas.commercepayments.read: Read the COMMERCE_PAYMENT properties.
            crm.objects.listings.write: Write listings
            crm.schemas.line_items.read: Line Items schemas
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.deals.highly_sensitive.read.v2: View deal records (highly-sensitive)
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.line_items.write: Line Items
            crm.schemas.invoices.read: Read invoices schema
            crm.objects.deals.sensitive.read.v2: ' '
            crm.objects.deals.write: ' '
            crm.objects.custom.highly_sensitive.read.v2: View custom object records
              (highly-sensitive)
            crm.objects.custom.highly_sensitive.write.v2: Change custom object records
              (highly-sensitive)
            crm.objects.subscriptions.write: Write to Commerce Subscriptions
            media_bridge.read: Read media and media events
            e-commerce: e-commerce
            crm.schemas.companies.read: ' '
            crm.schemas.quotes.read: Quotes schemas
            timeline: Create timeline events
            crm.objects.quotes.read: Quotes
            crm.objects.line_items.read: Line Items
            crm.objects.companies.sensitive.write.v2: ' '
            crm.objects.invoices.write: Write invoices
            crm.objects.marketing_events.write: Write marketing events
            crm.objects.users.read: Read User CRM objects
            crm.objects.deals.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.marketing_events.read: Read marketing events
            crm.objects.companies.read: ' '
            crm.objects.custom.write: Change custom object records
            tickets: Read and write tickets
            crm.objects.goals.write: Write goals
            crm.objects.custom.read: View custom object records
            crm.schemas.subscriptions.read: Read subscriptions schema
            crm.schemas.orders.read: Read order property settings
            crm.objects.services.read: Read services
            crm.objects.orders.read: Read Orders
            crm.schemas.appointments.read: Read appointments property settings
            crm.objects.companies.sensitive.read.v2: ' '
            crm.schemas.appointments.write: Write appointments property settings
            crm.schemas.companies.write: ' '
            crm.schemas.courses.write: Write courses property settings
            crm.pipelines.orders.write: "Create, delete, or make to your order pipelines\
              \ or their respective stages"
            crm.schemas.services.write: Write services property settings
            crm.schemas.listings.write: Write listings property settings
            crm.schemas.deals.write: ' '
            crm.schemas.carts.write: Write cart property settings
            crm.objects.carts.write: Write cart
            crm.schemas.invoices.write: Write invoices schema
            crm.schemas.orders.write: Write order property settings
            crm.schemas.subscriptions.write: Write to Subscription properties
            crm.objects.users.write: Write User CRM objects
            crm.objects.orders.write: Write orders
            crm.schemas.contacts.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: STARTER
