openapi: 3.0.1
info:
  title: Marketing Events
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    cms: STARTER
  x-hubspot-api-use-case: You have an external system that handles registration for
    your webinars and you want to ensure that attendee data and behavior is synced
    with your HubSpot CRM.
  x-hubspot-related-documentation:
  - name: Marketing Events Guide
    url: https://developers.hubspot.com/docs/guides/api/marketing/marketing-events
  x-hubspot-introduction: "A marketing event is a CRM object, similar to contacts\
    \ and companies, that enables you to track marketing events, such as a webinar,\
    \ along with the contacts who registered and attended the event. Below, learn\
    \ more about working with the marketing event API to integrate marketing events\
    \ into an app."
servers:
- url: https://api.hubapi.com
tags:
- name: Add event attendees
- name: Retrieve Participant State
- name: Subscriber State Changes
- name: Basic
- name: Batch
- name: List Associations
- name: Identifiers
- name: Change property
- name: Settings
paths:
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create:
    post:
      description: |-
        Records the participation of multiple HubSpot contacts in a Marketing Event using their HubSpot contact IDs.

        Additional Functionality:
        - Adds a timeline event to the contacts.

        Allowed Properties:
        For the state "attend":
        - joinedAt
        - leftAt
      operationId: "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_recordByContactIds"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Record Participants by ContactId with Marketing Event External Ids
      tags:
      - Add event attendees
  /marketing/v3/marketing-events/participations/{marketingEventId}/breakdown:
    get:
      description: Read Marketing event's participations breakdown with optional filters
        by internal identifier marketingEventId.
      operationId: "get-/marketing/v3/marketing-events/participations/{marketingEventId}/breakdown_getParticipationsBreakdownByMarketingEventId"
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read participations breakdown by Marketing Event internal identifier
      tags:
      - Retrieve Participant State
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert:
    post:
      description: "Record a subscriber state between multiple HubSpot contacts and\
        \ a marketing event, using HubSpot contact IDs. Note that the contact must\
        \ already exist in HubSpot; a contact will not be created."
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_upsertByContactId"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Record a subscriber state by contact ID
      tags:
      - Subscriber State Changes
  /marketing/v3/marketing-events/events/{externalEventId}:
    delete:
      description: |-
        Deletes the existing Marketing Event with the specified externalAccountId, externalEventId, if it exists.

        Only Marketing Events created by the same app can be deleted.
      operationId: "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Delete Marketing Event by External Ids
      tags:
      - Basic
    get:
      description: |-
        Returns the details of a Marketing Event with the specified externalAccountId, externalEventId, if it exists.

        Only Marketing Events created by the same app making the request can be retrieved.
      operationId: "get-/marketing/v3/marketing-events/events/{externalEventId}_getDetails"
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Get Marketing Event by External IDs
      tags:
      - Basic
    patch:
      description: |-
        Updates the details of an existing Marketing Event identified by its externalAccountId, externalEventId if it exists.

        Only Marketing Events created by the same app can be updated.
      operationId: "patch-/marketing/v3/marketing-events/events/{externalEventId}_update"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Update Marketing Event by External IDs
      tags:
      - Basic
    put:
      description: "Upserts a marketing event If there is an existing marketing event\
        \ with the specified ID, it will be updated; otherwise a new event will be\
        \ created."
      operationId: "put-/marketing/v3/marketing-events/events/{externalEventId}_upsert"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Create or update a marketing event
      tags:
      - Basic
  /marketing/v3/marketing-events/events/upsert:
    post:
      description: |-
        Upserts multiple Marketing Events. If a Marketing Event with the specified ID already exists, it will be updated; otherwise, a new event will be created.

        Only Marketing Events originally created by the same app can be updated.
      operationId: post-/marketing/v3/marketing-events/events/upsert_upsert
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Create or Update Multiple Marketing Events
      tags:
      - Batch
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create:
    post:
      description: |-
        Records the participation of multiple HubSpot contacts in a Marketing Event using their email addresses.

        If a contact does not exist, it will be automatically created. The contactProperties field is used exclusively for creating new contacts and will not update properties of existing contacts.

        Additional Functionality:
        - Adds a timeline event to the contacts.

        Allowed Properties:
        For the state "attend":
        - joinedAt
        - leftAt
      operationId: "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_recordByContactEmails"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Record Participants by Email with Marketing Event External Ids
      tags:
      - Add event attendees
  /marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown:
    get:
      description: Read Marketing event's participations breakdown with optional filters
        by externalAccountId and externalEventId pair.
      operationId: "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}/breakdown_getParticipationsBreakdownByExternalEventId"
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read participations breakdown by Marketing Event external identifier
      tags:
      - Retrieve Participant State
  /marketing/v3/marketing-events/{objectId}:
    delete:
      description: "Deletes the existing Marketing Event with the specified objectId,\
        \ if it exists."
      operationId: "delete-/marketing/v3/marketing-events/{objectId}_archiveByObjectId"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Delete Marketing Event by objectId
      tags:
      - Basic
    get:
      description: "Returns the details of a Marketing Event with the specified objectId,\
        \ if it exists."
      operationId: "get-/marketing/v3/marketing-events/{objectId}_getByObjectId"
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Get Marketing Event by objectId
      tags:
      - Basic
    patch:
      description: "Updates the details of an existing Marketing Event identified\
        \ by its objectId, if it exists."
      operationId: "patch-/marketing/v3/marketing-events/{objectId}_updateByObjectId"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Update Marketing Event by objectId
      tags:
      - Basic
  /marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists:
    get:
      description: Gets lists associated with a marketing event by external account
        id and external event id
      operationId: "get-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists_getAllByExternalAccountAndEventIds"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Get lists associated with a marketing event
      tags:
      - List Associations
  /marketing/v3/marketing-events/associations/{marketingEventId}/lists:
    get:
      description: Gets lists associated with a marketing event by marketing event
        id
      operationId: "get-/marketing/v3/marketing-events/associations/{marketingEventId}/lists_getAllByMarketingEventId"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Get lists associated with a marketing event
      tags:
      - List Associations
  /marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/email-create:
    post:
      description: |-
        Records the participation of multiple HubSpot contacts in a Marketing Event using their email addresses.

        If a contact does not exist, it will be automatically created. The contactProperties field is used exclusively for creating new contacts and will not update properties of existing contacts.

        Additional Functionality:
        - Adds a timeline event to the contacts.

        Allowed Properties:
        For the state "attend":
        - joinedAt
        - leftAt
      operationId: "post-/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/email-create_recordByEmail"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Record Participants by Email with Marketing Event Object Id
      tags:
      - Add event attendees
  /marketing/v3/marketing-events/:
    get:
      description: |-
        Returns all Marketing Events available on the portal, along with their properties, regardless of whether they were created manually or through the application.

        The marketing events returned by this endpoint are sorted by objectId.
      operationId: get-/marketing/v3/marketing-events/_getAll
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Get all marketing event
      tags:
      - Basic
  /marketing/v3/marketing-events/batch/update:
    post:
      description: "Updates multiple Marketing Events on the portal based on their\
        \ objectId, if they exist."
      operationId: post-/marketing/v3/marketing-events/batch/update_updateByObjectId
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Update Multiple Marketing Events by ObjectId
      tags:
      - Batch
  /marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/create:
    post:
      description: |-
        Records the participation of multiple HubSpot contacts in a Marketing Event using their HubSpot contact IDs.

        Additional Functionality:
        - Adds a timeline event to the contacts.

        Allowed Properties:
        For the state "attend":
        - joinedAt
        - leftAt
      operationId: "post-/marketing/v3/marketing-events/{objectId}/attendance/{subscriberState}/create_recordByContactId"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Record Participants by ContactId with Marketing Event Object Id
      tags:
      - Add event attendees
  /marketing/v3/marketing-events/batch/archive:
    post:
      description: |-
        Deletes multiple Marketing Events from the portal based on their objectId, if they exist.

        Responses:
        204: Returned if all specified Marketing Events were successfully deleted.
        207: Returned if some objectIds did not correspond to any existing Marketing Events.
      operationId: post-/marketing/v3/marketing-events/batch/archive_archiveByObjectId
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Delete Multiple Marketing Events by ObjectId
      tags:
      - Batch
  /marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}:
    get:
      description: Read Marketing event's participations counters by externalAccountId
        and externalEventId pair.
      operationId: "get-/marketing/v3/marketing-events/participations/{externalAccountId}/{externalEventId}_getParticipationsCountersByEventExternalId"
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read participations counters by Marketing Event external identifier
      tags:
      - Retrieve Participant State
  /marketing/v3/marketing-events/{externalEventId}/identifiers:
    get:
      description: |-
        This endpoint searches the portal for all Marketing Events whose externalEventId matches the value provided in the request.

        It retrieves the objectId and additional event details for each matching Marketing Event.

        Since multiple Marketing Events can have the same externalEventId, the endpoint returns all matching results.

        Note: Marketing Events become searchable by externalEventId a few minutes after creation.
      operationId: "get-/marketing/v3/marketing-events/{externalEventId}/identifiers_searchPortalEvents"
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Find Marketing Events by External Event Id
      tags:
      - Identifiers
  /marketing/v3/marketing-events/participations/{marketingEventId}:
    get:
      description: Read Marketing event's participations counters by internal identifier
        marketingEventId.
      operationId: "get-/marketing/v3/marketing-events/participations/{marketingEventId}_getParticipationsCountersByMarketingEventId"
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read participations counters by Marketing Event internal identifier
      tags:
      - Retrieve Participant State
  /marketing/v3/marketing-events/events/delete:
    post:
      description: "Deletes multiple Marketing Events based on externalAccountId,\
        \ externalEventId, and appId.\n\nOnly Marketing Events created by the same\
        \ apps will be deleted; events from other apps cannot be removed by this endpoint. "
      operationId: post-/marketing/v3/marketing-events/events/delete_archive
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Delete Multiple Marketing Events by External Ids
      tags:
      - Batch
  /marketing/v3/marketing-events/events/{externalEventId}/cancel:
    post:
      description: Mark a marketing event as cancelled.
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_cancel"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Mark a marketing event as cancelled
      tags:
      - Change property
  /marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}:
    delete:
      description: Disassociates a list from a marketing event by marketing event
        id and ILS list id
      operationId: "delete-/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}_disassociateByMarketingEventId"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Disassociate a list from a marketing event
      tags:
      - List Associations
    put:
      description: Associates a list with a marketing event by marketing event id
        and ILS list id
      operationId: "put-/marketing/v3/marketing-events/associations/{marketingEventId}/lists/{listId}_associateByMarketingEventId"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Associate a list with a marketing event
      tags:
      - List Associations
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert:
    post:
      description: "Record a subscriber state between multiple HubSpot contacts and\
        \ a marketing event, using contact email addresses. Note that the contact\
        \ must already exist in HubSpot; a contact will not be created. The contactProperties\
        \ field is used only when creating a new contact. These properties will not\
        \ update existing contacts. "
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_upsertByContactEmail"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Record a subscriber state by contact email
      tags:
      - Subscriber State Changes
  /marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}:
    delete:
      description: "Disassociates a list from a marketing event by external account\
        \ id, external event id, and ILS list id"
      operationId: "delete-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}_disassociateByExternalAccountAndEventIds"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Disassociate a list from a marketing event
      tags:
      - List Associations
    put:
      description: "Associates a list with a marketing event by external account id,\
        \ external event id, and ILS list id"
      operationId: "put-/marketing/v3/marketing-events/associations/{externalAccountId}/{externalEventId}/lists/{listId}_associateByExternalAccountAndEventIds"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Associate a list with a marketing event
      tags:
      - List Associations
  /marketing/v3/marketing-events/events/{externalEventId}/complete:
    post:
      description: Mark a marketing event as completed
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete"
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Mark a marketing event as completed
      tags:
      - Change property
  /marketing/v3/marketing-events/events:
    post:
      description: Creates a new marketing event in HubSpot
      operationId: post-/marketing/v3/marketing-events/events_create
      security:
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      summary: Create a marketing event
      tags:
      - Basic
  /marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown:
    get:
      description: Read Contact's participations by identifier - email or internal
        id.
      operationId: "get-/marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown_getParticipationsBreakdownByContactId"
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read participations breakdown by Contact identifier
      tags:
      - Retrieve Participant State
  /marketing/v3/marketing-events/{appId}/settings:
    get:
      description: Retrieve the current settings for the application.
      operationId: "get-/marketing/v3/marketing-events/{appId}/settings_getAll"
      security:
      - developer_hapikey: []
      summary: Retrieve the application settings
      tags:
      - Settings
    post:
      description: Create or update the current settings for the application.
      operationId: "post-/marketing/v3/marketing-events/{appId}/settings_update"
      security:
      - developer_hapikey: []
      summary: Update the application settings
      tags:
      - Settings
  /marketing/v3/marketing-events/events/search:
    get:
      description: |-
        Retrieves Marketing Events where the externalEventId matches the value provided in the request, limited to events created by the app making the request.

        Marketing Events created by other apps will not be included in the results.
      operationId: get-/marketing/v3/marketing-events/events/search_doSearch
      security:
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Find App-Specific Marketing Events by External Event Id
      tags:
      - Identifiers
components:
  securitySchemes:
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.marketing_events.read: Read marketing events
            crm.objects.marketing_events.write: Write marketing events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  cms: STARTER
