openapi: 3.0.1
info:
  title: CRM Calling Extensions
  version: v3
  x-hubspot-product-tier-requirements:
    sales: STARTER
    service: STARTER
  x-hubspot-api-use-case: "Create an integration for a third-party calling service\
    \ that your company uses, rather than using HubSpot's native calling tool."
  x-hubspot-related-documentation:
  - name: Call SDK Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/extensions/calling-sdk
  x-hubspot-introduction: Use the calling extensions SDK to provide HubSpot users
    with custom calling options on CRM records.
servers:
- url: https://api.hubapi.com
tags:
- name: Settings
- name: Recording settings
- name: Channel Connection Settings
paths:
  /crm/v3/extensions/calling/{appId}/settings:
    delete:
      description: Delete a calling extension. This will remove your service as an
        option for all connected accounts.
      operationId: "delete-/crm/v3/extensions/calling/{appId}/settings_archive"
      security:
      - developer_hapikey: []
      summary: Delete calling settings
      tags:
      - Settings
    get:
      description: Retrieve the settings configured for the app.
      operationId: "get-/crm/v3/extensions/calling/{appId}/settings_getById"
      security:
      - developer_hapikey: []
      summary: Retrieve settings
      tags:
      - Settings
    patch:
      description: Update existing calling extension settings.
      operationId: "patch-/crm/v3/extensions/calling/{appId}/settings_update"
      security:
      - developer_hapikey: []
      summary: Update settings
      tags:
      - Settings
    post:
      description: "Set the menu label, target iframe URL, and dimensions for your\
        \ calling extension."
      operationId: "post-/crm/v3/extensions/calling/{appId}/settings_create"
      security:
      - developer_hapikey: []
      summary: Configure a calling extension
      tags:
      - Settings
  /crm/v3/extensions/calling/{appId}/settings/recording:
    get:
      description: "Retrieve the URL that is registered for [call recording](https://developers.hubspot.com/docs/guides/apps/extensions/calling-extensions/recordings-and-transcriptions#register-your-app-s-endpoint-with-hubspot-using-the-calling-settings-api)."
      operationId: "get-/crm/v3/extensions/calling/{appId}/settings/recording_getUrlFormat"
      security:
      - developer_hapikey: []
      summary: Retrieve recording settings
      tags:
      - Recording settings
    patch:
      description: "Update the URL that HubSpot will use to retrieve [call recordings](https://developers.hubspot.com/docs/guides/apps/extensions/calling-extensions/recordings-and-transcriptions#register-your-app-s-endpoint-with-hubspot-using-the-calling-settings-api)."
      operationId: "patch-/crm/v3/extensions/calling/{appId}/settings/recording_updateUrlFormat"
      security:
      - developer_hapikey: []
      summary: Update recording settings
      tags:
      - Recording settings
    post:
      description: "Register an external URL that HubSpot will use to retrieve [call\
        \ recordings](https://developers.hubspot.com/docs/guides/apps/extensions/calling-extensions/recordings-and-transcriptions#register-your-app-s-endpoint-with-hubspot-using-the-calling-settings-api)."
      operationId: "post-/crm/v3/extensions/calling/{appId}/settings/recording_registerUrlFormat"
      security:
      - developer_hapikey: []
      summary: Enable the app for call recording
      tags:
      - Recording settings
  /crm/v3/extensions/calling/recordings/ready:
    post:
      description: "Mark a call recording as ready for transcription, specifying the\
        \ call by its ID (`engagementid`)."
      operationId: post-/crm/v3/extensions/calling/recordings/ready_markAsReady
      security:
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      summary: Mark recording as ready for transcription
      tags:
      - Recording settings
  /crm/v3/extensions/calling/{appId}/settings/channel-connection:
    delete:
      description: "Delete the [channel connection settings](https://developers.hubspot.com/docs/guides/api/crm/extensions/third-party-calling#delete-existing-channel-connection-settings)\
        \ for the app."
      operationId: "delete-/crm/v3/extensions/calling/{appId}/settings/channel-connection_archive"
      security:
      - developer_hapikey: []
      summary: Delete channel connection settings
      tags:
      - Channel Connection Settings
    get:
      description: "Retrieve the settings related to the app's [channel connection](https://developers.hubspot.com/docs/guides/api/crm/extensions/third-party-calling#fetch-existing-channel-connection-settings)."
      operationId: "get-/crm/v3/extensions/calling/{appId}/settings/channel-connection_getById"
      security:
      - developer_hapikey: []
      summary: Retrieve channel connection settings
      tags:
      - Channel Connection Settings
    patch:
      description: "Update existing [channel connection settings](https://developers.hubspot.com/docs/guides/api/crm/extensions/third-party-calling#manage-the-webhook-settings-for-channel-connection)\
        \ for your app."
      operationId: "patch-/crm/v3/extensions/calling/{appId}/settings/channel-connection_update"
      security:
      - developer_hapikey: []
      summary: Update channel connection settings
      tags:
      - Channel Connection Settings
    post:
      description: "Configure [channel connection settings](https://developers.hubspot.com/docs/guides/api/crm/extensions/third-party-calling#create-channel-connection-settings)\
        \ for the app. "
      operationId: "post-/crm/v3/extensions/calling/{appId}/settings/channel-connection_create"
      security:
      - developer_hapikey: []
      summary: Configure channel connection settings
      tags:
      - Channel Connection Settings
components:
  securitySchemes:
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.contacts.write: ' '
            crm.schemas.contacts.write: ' '
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.schemas.contacts.read: ' '
            crm.objects.contacts.read: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  sales: STARTER
  service: STARTER
