openapi: 3.0.1
info:
  description: Meetings Service For HubSpot Sales
  title: Scheduler Meetings
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: PROFESSIONAL
    sales: PROFESSIONAL
    service: PROFESSIONAL
    cms: PROFESSIONAL
  x-hubspot-api-use-case: "You need to get a list of meeting links or book meetings,\
    \ or you need to create an interface so customers can book meetings with your\
    \ team."
  x-hubspot-related-documentation:
  - name: Meetings guide
    url: https://developers.hubspot.com/docs/reference/api/crm/engagements/meetings
  x-hubspot-introduction: Use the Meetings links API to retrieve information about
    meetings created through a scheduling page. You can also book a meeting with a
    scheduling page through the API.
servers:
- url: https://api.hubapi.com
tags:
- name: Meetings links
paths:
  /scheduler/v3/meetings/meeting-links/book/{slug}:
    get:
      operationId: "get-/scheduler/v3/meetings/meeting-links/book/{slug}"
      security:
      - oauth2:
        - scheduler.meetings.meeting-link.read
      - private_apps:
        - scheduler.meetings.meeting-link.read
      tags:
      - Meetings links
  /scheduler/v3/meetings/meeting-links:
    get:
      operationId: get-/scheduler/v3/meetings/meeting-links
      security:
      - oauth2:
        - scheduler.meetings.meeting-link.read
      - private_apps:
        - scheduler.meetings.meeting-link.read
      tags:
      - Meetings links
  /scheduler/v3/meetings/meeting-links/book:
    post:
      operationId: post-/scheduler/v3/meetings/meeting-links/book
      security:
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.goals.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.appointments.sensitive.write
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.schemas.contacts.write
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.schemas.contacts.write
        - tickets
      - oauth2:
        - crm.schemas.contacts.write
        - tickets
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.companies.sensitive.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.schemas.contacts.write
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.line_items.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.deals.highly_sensitive.write
      - private_apps:
        - crm.objects.listings.write
        - crm.schemas.contacts.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.listings.write
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.companies.highly_sensitive.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
        - crm.schemas.contacts.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.companies.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.appointments.sensitive.write.v2
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.appointments.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.courses.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.courses.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.appointments.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.write
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.contacts.write
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.contacts.write
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.services.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.services.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
        - crm.schemas.contacts.write
      tags:
      - Meetings links
  /scheduler/v3/meetings/meeting-links/book/availability-page/{slug}:
    get:
      operationId: "get-/scheduler/v3/meetings/meeting-links/book/availability-page/{slug}"
      security:
      - oauth2:
        - scheduler.meetings.meeting-link.read
      - private_apps:
        - scheduler.meetings.meeting-link.read
      tags:
      - Meetings links
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            scheduler.meetings.meeting-link.read: Read from meeting links
            crm.schemas.contacts.write: ' '
            crm.objects.goals.write: Write goals
            crm.objects.courses.write: Write courses
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.objects.services.write: Write services
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.listings.write: Write listings
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.contacts.write: ' '
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
            crm.objects.companies.sensitive.write.v2: ' '
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.line_items.write: Line Items
            crm.objects.appointments.write: Write appointments
            crm.objects.deals.write: ' '
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            tickets: Read and write tickets
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
