openapi: 3.0.1
info:
  title: Lists
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: STARTER
    cms: STARTER
  x-hubspot-api-use-case: "You want to bulk add contacts to a particular list, or\
    \ remove company records from a company list."
  x-hubspot-related-documentation:
  - name: Lists Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/lists/overview
  x-hubspot-introduction: Use the lists API to manage list memberships for object
    lists.
servers:
- url: https://api.hubapi.com
tags:
- name: Lists
- name: Memberships
- name: Folders
- name: Mapping
paths:
  /crm/v3/lists/{listId}/update-list-name:
    put:
      description: Update the name of a list. The name must be globally unique relative
        to all other public lists in the portal.
      operationId: "put-/crm/v3/lists/{listId}/update-list-name_updateName"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Update List Name
      tags:
      - Lists
  /crm/v3/lists/{listId}/memberships/add-and-remove:
    put:
      description: |-
        Add and/or remove records that have already been created in the system to and/or from a list.

        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.
      operationId: "put-/crm/v3/lists/{listId}/memberships/add-and-remove_addAndRemove"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Add and/or Remove Records from a List
      tags:
      - Memberships
  /crm/v3/lists/{listId}:
    delete:
      description: "Delete a list by **ILS list ID**. Lists deleted through this endpoint\
        \ can be restored up to 90-days following the delete. After 90-days, the list\
        \ is purged and can no longer be restored."
      operationId: "delete-/crm/v3/lists/{listId}_remove"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Delete a List
      tags:
      - Lists
    get:
      description: Fetch a single list by **ILS list ID**.
      operationId: "get-/crm/v3/lists/{listId}_getById"
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch List by ID
      tags:
      - Lists
  /crm/v3/lists/{listId}/update-list-filters:
    put:
      description: "Update the filter branch definition of a `DYNAMIC` list. Once\
        \ updated, the list memberships will be re-evaluated and updated to match\
        \ the new definition."
      operationId: "put-/crm/v3/lists/{listId}/update-list-filters_updateListFilters"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Update List Filter Definition
      tags:
      - Lists
  /crm/v3/lists/search:
    post:
      description: Search lists by list name or page through all lists by providing
        an empty `query` value.
      operationId: post-/crm/v3/lists/search_doSearch
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Search Lists
      tags:
      - Lists
  /crm/v3/lists/folders/move-list:
    put:
      description: "Given a list and a folder, the list will be moved to that folder."
      operationId: put-/crm/v3/lists/folders/move-list_moveList
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Moves a list to a given folder
      tags:
      - Folders
  /crm/v3/lists/{listId}/memberships/add:
    put:
      description: |-
        Add the records provided to the list. Records that do not exist or that are already members of the list are ignored.

        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.
      operationId: "put-/crm/v3/lists/{listId}/memberships/add_add"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Add Records to a List
      tags:
      - Memberships
  /crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}:
    get:
      description: Fetch a single list by list name and object type.
      operationId: "get-/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}_getByName"
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch List by Name
      tags:
      - Lists
  /crm/v3/lists/folders/{folderId}/move/{newParentFolderId}:
    put:
      description: This moves the folder from its current location to a new location.
        It updates the parent of this folder to the new Id given.
      operationId: "put-/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}_move"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Moves a folder
      tags:
      - Folders
  /crm/v3/lists/idmapping:
    get:
      description: "This API allows translation of legacy list id to list id. This\
        \ is a temporary API allowed for mapping old id's to new id's and will expire\
        \ on May 30th, 2025."
      operationId: get-/crm/v3/lists/idmapping_translateLegacyListIdToListId
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Translate Legacy List Id to Modern List Id
      tags:
      - Mapping
    post:
      description: "This API allows translation of a batch of legacy list id's to\
        \ list id's. This allows for a maximum of 10,000 id's. This is a temporary\
        \ API allowed for mapping old id's to new id's and will expire on May 30th,\
        \ 2025."
      operationId: post-/crm/v3/lists/idmapping_translateLegacyListIdToListIdBatch
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Translate Legacy List Id to Modern List Id in Batch
      tags:
      - Mapping
  /crm/v3/lists/{listId}/restore:
    put:
      description: Restore a previously deleted list by **ILS list ID**. Deleted lists
        are eligible to be restored up-to 90-days after the list has been deleted.
      operationId: "put-/crm/v3/lists/{listId}/restore_restore"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Restore a List
      tags:
      - Lists
  /crm/v3/lists/folders/{folderId}/rename:
    put:
      description: Renames the given folderId with a new name.
      operationId: "put-/crm/v3/lists/folders/{folderId}/rename_rename"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Rename a folder
      tags:
      - Folders
  /crm/v3/lists/{listId}/memberships/join-order:
    get:
      description: |-
        Fetch the memberships of a list in order sorted by the time the records were added to the list.

        The `recordId`s are sorted in *ascending* order if an `after` offset or no offset is provided. If only a `before` offset is provided, then the records are sorted in *descending* order.

        The `after` offset parameter will take precedence over the `before` offset in a case where both are provided.
      operationId: "get-/crm/v3/lists/{listId}/memberships/join-order_getPageOrderedByAddedToListDate"
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch List Memberships Ordered by Added to List Date
      tags:
      - Memberships
  /crm/v3/lists/{listId}/memberships/add-from/{sourceListId}:
    put:
      description: |-
        Add all of the records from a *source list* (specified by the `sourceListId`) to a *destination list* (specified by the `listId`). Records that are already members of the *destination list* will be ignored. The *destination* and *source list* IDs must be different. The *destination* and *source lists* must contain records of the same type (e.g. contacts, companies, etc.).

        This endpoint only works for *destination lists* that have a `processingType` of `MANUAL` or `SNAPSHOT`. The *source list* can have any `processingType`.

        This endpoint only supports a `sourceListId` for lists with less than 100,000 memberships.
      operationId: "put-/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}_addAllFromList"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Add All Records from a Source List to a Destination List
      tags:
      - Memberships
  /crm/v3/lists/records/{objectTypeId}/{recordId}/memberships:
    get:
      description: For given record provide lists this record is member of.
      operationId: "get-/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships_getLists"
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Get lists record is member of
      tags:
      - Memberships
  /crm/v3/lists/:
    get:
      description: Fetch multiple lists in a single request by **ILS list ID**. The
        response will include the definitions of all lists that exist for the `listIds`
        provided.
      operationId: get-/crm/v3/lists/_getAll
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch Multiple Lists
      tags:
      - Lists
    post:
      description: Create a new list with the provided object list definition.
      operationId: post-/crm/v3/lists/_create
      security:
      - private_apps:
        - cms.membership.access_groups.write
      - oauth2:
        - cms.membership.access_groups.write
      - oauth2:
        - crm.lists.write
      - private_apps:
        - crm.lists.write
      summary: Create List
      tags:
      - Lists
  /crm/v3/lists/folders:
    get:
      description: Retrieves a folder and recursively includes all folders via the
        childNodes attribute.  The child lists field will be empty in all child nodes.
        Only the folder retrieved will include the child lists in that folder.
      operationId: get-/crm/v3/lists/folders_getAll
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Retrieves a folder.
      tags:
      - Folders
    post:
      description: Creates a folder with the given information.
      operationId: post-/crm/v3/lists/folders_create
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Creates a folder
      tags:
      - Folders
  /crm/v3/lists/folders/{folderId}:
    delete:
      description: Deletes the folder with the given Id.
      operationId: "delete-/crm/v3/lists/folders/{folderId}_remove"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Deletes a folder
      tags:
      - Folders
  /crm/v3/lists/{listId}/memberships:
    delete:
      description: |-
        Remove **all** of the records from a list. ***Note:*** *The list is not deleted.*

        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.

        This endpoint only supports lists that have less than 100,000 memberships.
      operationId: "delete-/crm/v3/lists/{listId}/memberships_removeAll"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Delete All Records from a List
      tags:
      - Memberships
    get:
      description: |-
        Fetch the memberships of a list in order sorted by the `recordId` of the records in the list.

        The `recordId`s are sorted in *ascending* order if an `after` offset or no offset is provided. If only a `before` offset is provided, then the records are sorted in *descending* order.

        The `after` offset parameter will take precedence over the `before` offset in a case where both are provided.
      operationId: "get-/crm/v3/lists/{listId}/memberships_getPage"
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch List Memberships Ordered by ID
      tags:
      - Memberships
  /crm/v3/lists/{listId}/memberships/remove:
    put:
      description: |-
        Remove the records provided from the list. Records that do not exist or that are not members of the list are ignored.

        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.
      operationId: "put-/crm/v3/lists/{listId}/memberships/remove_remove"
      security:
      - oauth2:
        - cms.membership.access_groups.write
        - crm.lists.read
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
      - private_apps:
        - cms.membership.access_groups.write
        - crm.lists.read
      summary: Remove Records from a List
      tags:
      - Memberships
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.lists.read: ' '
            cms.membership.access_groups.write: Write membership access groups.
            crm.lists.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: STARTER
  cms: STARTER
