openapi: 3.0.1
info:
  description: ""
  title: Feedback Submissions
  version: v3
  x-hubspot-product-tier-requirements:
    service: PROFESSIONAL
  x-hubspot-api-use-case: "To prepare for an upcoming product redesign, programmatically\
    \ retrieve all feedback survey responses to better understand customer sentiment."
  x-hubspot-related-documentation:
  - name: Feedback Submissions Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/objects/feedback-submissions
  x-hubspot-introduction: "Use the feedback submissions API to retrieve information\
    \ submitted to your NPS, CSAT, CES, and custom feedback surveys."
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Basic
- name: Search
paths:
  /crm/v3/objects/feedback_submissions/batch/read:
    post:
      description: 'Retrieve records by record ID or include the `idProperty` parameter
        to retrieve records by a custom unique value property. '
      operationId: post-/crm/v3/objects/feedback_submissions/batch/read_read
      security:
      - oauth2_legacy: []
      - oauth2:
        - crm.objects.feedback_submissions.read
        - crm.objects.contacts.read
      - private_apps_legacy: []
      - private_apps:
        - crm.objects.feedback_submissions.read
        - crm.objects.contacts.read
      summary: "Read a batch of feedback submissions by internal ID, or unique property\
        \ values"
      tags:
      - Batch
  /crm/v3/objects/feedback_submissions/{feedbackSubmissionId}:
    get:
      description: "Read an Object identified by `{feedbackSubmissionId}`. `{feedbackSubmissionId}`\
        \ refers to the internal object ID by default, or optionally any unique property\
        \ value as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: "get-/crm/v3/objects/feedback_submissions/{feedbackSubmissionId}_getById"
      security:
      - oauth2_legacy: []
      - oauth2:
        - crm.objects.feedback_submissions.read
        - crm.objects.contacts.read
      - private_apps_legacy: []
      - private_apps:
        - crm.objects.feedback_submissions.read
        - crm.objects.contacts.read
      summary: Read
      tags:
      - Basic
  /crm/v3/objects/feedback_submissions:
    get:
      description: Read a page of feedback submissions. Control what is returned via
        the `properties` query param.
      operationId: get-/crm/v3/objects/feedback_submissions_getPage
      security:
      - oauth2_legacy: []
      - oauth2:
        - crm.objects.feedback_submissions.read
        - crm.objects.contacts.read
      - private_apps_legacy: []
      - private_apps:
        - crm.objects.feedback_submissions.read
        - crm.objects.contacts.read
      summary: List
      tags:
      - Basic
  /crm/v3/objects/feedback_submissions/search:
    post:
      operationId: post-/crm/v3/objects/feedback_submissions/search_doSearch
      security:
      - oauth2_legacy: []
      - oauth2:
        - crm.objects.feedback_submissions.read
        - crm.objects.contacts.read
      - private_apps_legacy: []
      - private_apps:
        - crm.objects.feedback_submissions.read
        - crm.objects.contacts.read
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.objects.appointments.read: Read appointments
            crm.objects.orders.write: Write orders
            crm.objects.custom.sensitive.write.v2: Change custom object records (sensitive)
            crm.objects.carts.read: Read carts
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
            crm.objects.users.write: Write User CRM objects
            crm.objects.services.write: Write services
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.custom.write: Change custom object records
            crm.objects.quotes.read: Quotes
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.custom.highly_sensitive.read.v2: View custom object records
              (highly-sensitive)
            crm.objects.goals.write: Write goals
            crm.objects.custom.sensitive.read.v2: View custom object records (sensitive)
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.appointments.sensitive.read.v2: Read appointments (sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.deals.write: ' '
            crm.objects.leads.write: Modify lead objects
            crm.objects.companies.read: ' '
            crm.objects.listings.read: Read listings
            crm.objects.deals.highly_sensitive.read.v2: View deal records (highly-sensitive)
            crm.objects.contacts.write: ' '
            crm.objects.carts.write: Write cart
            crm.objects.companies.sensitive.read.v2: ' '
            crm.objects.invoices.read: Read invoices objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.invoices.write: Write invoices
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            crm.objects.goals.read: Read goals
            crm.objects.custom.highly_sensitive.write.v2: Change custom object records
              (highly-sensitive)
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.appointments.write: Write appointments
            media_bridge.read: Read media and media events
            crm.objects.line_items.write: Line Items
            crm.objects.orders.read: Read Orders
            crm.objects.subscriptions.write: Write to Commerce Subscriptions
            crm.objects.contacts.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.quotes.write: Quotes
            crm.objects.deals.sensitive.read.v2: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.users.read: Read User CRM objects
            tickets: Read and write tickets
            crm.objects.companies.sensitive.write.v2: ' '
            crm.objects.leads.read: Read lead objects
            crm.objects.services.read: Read services
            crm.objects.courses.write: Write courses
            crm.objects.custom.read: View custom object records
            crm.objects.listings.write: Write listings
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.deals.read: ' '
            crm.objects.companies.highly_sensitive.read.v2: View company records (highly-sensitive)
            e-commerce: e-commerce
            crm.objects.feedback_submissions.read: ""
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  service: PROFESSIONAL
