openapi: 3.0.1
info:
  title: Limits Tracking
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-api-use-case: "Before importing a large file of contacts, you want to\
    \ check how many contact records you've created compared to your account's limit."
  x-hubspot-related-documentation:
  - name: Limits tracking guide
    url: https://developers.hubspot.com/docs/guides/api/crm/limits-tracking
  x-hubspot-introduction: "Use the limits tracking API to view limits and usage for\
    \ CRM data including records, associations, pipelines, and properties."
servers:
- url: https://api.hubapi.com
tags:
- name: Limits
paths:
  /crm/v3/limits/associations/labels:
    get:
      description: Returns limits and usage for custom association labels
      operationId: get-/crm/v3/limits/associations/labels
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read association label limits
      tags:
      - Limits
  /crm/v3/limits/associations/records/{fromObjectTypeId}/{toObjectTypeId}:
    get:
      description: Returns records approaching or at association limits between two
        objects
      operationId: "get-/crm/v3/limits/associations/records/{fromObjectTypeId}/{toObjectTypeId}"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read record association limits between two objects
      tags:
      - Limits
  /crm/v3/limits/associations/records/{fromObjectTypeId}/to:
    get:
      description: Returns objects for which the from object has records approaching
        or at association limits
      operationId: "get-/crm/v3/limits/associations/records/{fromObjectTypeId}/to"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read record association limits from an object
      tags:
      - Limits
  /crm/v3/limits/custom-object-types:
    get:
      description: Returns limits and usage for custom object schemas
      operationId: get-/crm/v3/limits/custom-object-types
      security:
      - oauth2:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.custom.sensitive.write
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      summary: Read custom object limits
      tags:
      - Limits
  /crm/v3/limits/custom-properties:
    get:
      description: Returns limits and usage per object for custom properties
      operationId: get-/crm/v3/limits/custom-properties
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read custom property limits
      tags:
      - Limits
  /crm/v3/limits/associations/records/from:
    get:
      description: Returns objects with records approaching or at association limits
      operationId: get-/crm/v3/limits/associations/records/from
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read record association limits
      tags:
      - Limits
  /crm/v3/limits/records:
    get:
      description: Returns limits and usage per object for records
      operationId: get-/crm/v3/limits/records
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read record limits
      tags:
      - Limits
  /crm/v3/limits/pipelines:
    get:
      description: Returns limits and usage per object for pipelines
      operationId: get-/crm/v3/limits/pipelines
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read pipeline limits
      tags:
      - Limits
  /crm/v3/limits/calculated-properties:
    get:
      description: Returns overall limit and per object usage for calculated properties
      operationId: get-/crm/v3/limits/calculated-properties
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read calculation property limits
      tags:
      - Limits
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.users.write: Write User CRM objects
            crm.objects.services.write: Write services
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.custom.write: Change custom object records
            crm.objects.quotes.read: Quotes
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.custom.highly_sensitive.read.v2: View custom object records
              (highly-sensitive)
            crm.objects.goals.write: Write goals
            crm.objects.custom.sensitive.read.v2: View custom object records (sensitive)
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.appointments.sensitive.read.v2: Read appointments (sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.deals.write: ' '
            crm.objects.leads.write: Modify lead objects
            crm.objects.companies.read: ' '
            crm.objects.listings.read: Read listings
            crm.objects.deals.highly_sensitive.read.v2: View deal records (highly-sensitive)
            crm.objects.contacts.write: ' '
            crm.objects.carts.write: Write cart
            crm.objects.companies.sensitive.read.v2: ' '
            crm.objects.invoices.read: Read invoices objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.invoices.write: Write invoices
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            crm.objects.goals.read: Read goals
            crm.objects.custom.highly_sensitive.write.v2: Change custom object records
              (highly-sensitive)
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.appointments.write: Write appointments
            media_bridge.read: Read media and media events
            crm.objects.line_items.write: Line Items
            crm.objects.orders.read: Read Orders
            crm.objects.subscriptions.write: Write to Commerce Subscriptions
            crm.objects.contacts.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.quotes.write: Quotes
            crm.objects.deals.sensitive.read.v2: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.users.read: Read User CRM objects
            tickets: Read and write tickets
            crm.objects.companies.sensitive.write.v2: ' '
            crm.objects.leads.read: Read lead objects
            crm.objects.services.read: Read services
            crm.objects.courses.write: Write courses
            crm.objects.custom.read: View custom object records
            crm.objects.listings.write: Write listings
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.deals.read: ' '
            crm.objects.companies.highly_sensitive.read.v2: View company records (highly-sensitive)
            e-commerce: e-commerce
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.objects.appointments.read: Read appointments
            crm.objects.orders.write: Write orders
            crm.objects.custom.sensitive.write.v2: Change custom object records (sensitive)
            crm.objects.carts.read: Read carts
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
            crm.schemas.custom.read: View custom object definitions
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
