openapi: 3.0.1
info:
  title: Associations Schema
  version: v4
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: STARTER
  x-hubspot-api-use-case: "To associate a contact with a company, use this API to\
    \ get the necessary associationTypeId and associationCategory."
  x-hubspot-related-documentation:
  - name: Associations Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4
  x-hubspot-introduction: "Use the association schema API to understand how different\
    \ types of CRM records and activities can relate to one another, as well as define\
    \ your own custom associations. "
servers:
- url: https://api.hubapi.com
tags:
- name: Definition Configurations
- name: Definitions
paths:
  /crm/v4/associations/definitions/configurations/all:
    get:
      description: Returns all user configurations available on a given portal
      operationId: get-/crm/v4/associations/definitions/configurations/all_getAll
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read All
      tags:
      - Definition Configurations
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}:
    get:
      description: Returns user configurations on all association definitions between
        two object types
      operationId: "get-/crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}_getAllBetweenTwoObjectTypes"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read
      tags:
      - Definition Configurations
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/create:
    post:
      description: Batch create user configurations between two object types
      operationId: "post-/crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/create_batchCreate"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Create
      tags:
      - Definition Configurations
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/{fromObjectType}/{toObjectType}/labels:
    get:
      description: Returns all association types between two object types
      operationId: "get-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_getAll"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Read
      tags:
      - Definitions
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
    post:
      description: Create a user defined association definition
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_create"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Create
      tags:
      - Definitions
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
    put:
      description: Update a user defined association definition
      operationId: "put-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_update"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Update
      tags:
      - Definitions
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/purge:
    post:
      description: Batch delete user configurations between two object types
      operationId: "post-/crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/purge_batchRemove"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Delete
      tags:
      - Definition Configurations
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/{fromObjectType}/{toObjectType}/labels/{associationTypeId}:
    delete:
      description: Deletes an association definition
      operationId: "delete-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels/{associationTypeId}_remove"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Delete
      tags:
      - Definitions
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/update:
    post:
      description: Batch update user configurations between two object types
      operationId: "post-/crm/v4/associations/definitions/configurations/{fromObjectType}/{toObjectType}/batch/update_batchUpdate"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.objects.quotes.write
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - media_bridge.read
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      summary: Update
      tags:
      - Definition Configurations
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.users.write: Write User CRM objects
            crm.objects.services.write: Write services
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.custom.write: Change custom object records
            crm.objects.quotes.read: Quotes
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.custom.highly_sensitive.read.v2: View custom object records
              (highly-sensitive)
            crm.objects.goals.write: Write goals
            crm.objects.custom.sensitive.read.v2: View custom object records (sensitive)
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.appointments.sensitive.read.v2: Read appointments (sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.deals.write: ' '
            crm.objects.leads.write: Modify lead objects
            crm.objects.companies.read: ' '
            crm.objects.listings.read: Read listings
            crm.objects.deals.highly_sensitive.read.v2: View deal records (highly-sensitive)
            crm.objects.contacts.write: ' '
            crm.objects.carts.write: Write cart
            crm.objects.companies.sensitive.read.v2: ' '
            crm.objects.invoices.read: Read invoices objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.invoices.write: Write invoices
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            crm.objects.goals.read: Read goals
            crm.objects.custom.highly_sensitive.write.v2: Change custom object records
              (highly-sensitive)
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.appointments.write: Write appointments
            media_bridge.read: Read media and media events
            crm.objects.line_items.write: Line Items
            crm.objects.orders.read: Read Orders
            crm.objects.subscriptions.write: Write to Commerce Subscriptions
            crm.objects.contacts.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.quotes.write: Quotes
            crm.objects.deals.sensitive.read.v2: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.users.read: Read User CRM objects
            tickets: Read and write tickets
            crm.objects.companies.sensitive.write.v2: ' '
            crm.objects.leads.read: Read lead objects
            crm.objects.services.read: Read services
            crm.objects.courses.write: Write courses
            crm.objects.custom.read: View custom object records
            crm.objects.listings.write: Write listings
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.deals.read: ' '
            crm.objects.companies.highly_sensitive.read.v2: View company records (highly-sensitive)
            e-commerce: e-commerce
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.objects.appointments.read: Read appointments
            crm.objects.orders.write: Write orders
            crm.objects.custom.sensitive.write.v2: Change custom object records (sensitive)
            crm.objects.carts.read: Read carts
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: STARTER
