openapi: 3.0.1
info:
  title: Conversations Inbox & Messages
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-api-use-case: "If you're using the conversations inbox in HubSpot, but\
    \ you want to report on support agent productivity in an external tool or export\
    \ message data to an external service, you can build an integration with the conversations\
    \ and messages API."
  x-hubspot-related-documentation:
  - name: Inbox & Messages Guide
    url: https://developers.hubspot.com/docs/guides/api/conversations/inbox-and-messages
  x-hubspot-introduction: "Use the conversations API to manage and send messages via\
    \ the connected channels in your conversations inbox. You can retrieve existing\
    \ messages, update threads, and provide internal comments for agents on your team. "
servers:
- url: https://api.hubapi.com
tags:
- name: Conversations
paths:
  /conversations/v3/conversations/inboxes:
    get:
      operationId: get-/conversations/v3/conversations/inboxes
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get conversations inboxes.
      tags:
      - Conversations
  /conversations/v3/conversations/threads/{threadId}:
    delete:
      description: Archives a single thread. The thread will be permanently deleted
        30 days after placed in an archived state.
      operationId: "delete-/conversations/v3/conversations/threads/{threadId}"
      security:
      - private_apps:
        - conversations.write
      - oauth2:
        - conversations.write
      summary: Archives a thread.
      tags:
      - Conversations
    get:
      description: Returns a single thread.
      operationId: "get-/conversations/v3/conversations/threads/{threadId}"
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get a single thread.
      tags:
      - Conversations
    patch:
      description: "Updates a single thread. Either a thread's status can be updated,\
        \ or the thread can be restored."
      operationId: "patch-/conversations/v3/conversations/threads/{threadId}"
      security:
      - private_apps:
        - conversations.write
      - oauth2:
        - conversations.write
      summary: Update a thread.
      tags:
      - Conversations
  /conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content:
    get:
      description: Returns the complete original text and rich text bodies of a message.
        This will be different from the text and rich text in the message itself if
        the message's `truncationStatus` is anything other than `NOT_TRUNCATED`.
      operationId: "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content"
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get the original content of a single message.
      tags:
      - Conversations
  /conversations/v3/conversations/threads/{threadId}/messages:
    get:
      operationId: "get-/conversations/v3/conversations/threads/{threadId}/messages"
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get message history for a thread.
      tags:
      - Conversations
    post:
      description: Send a new message on a thread at the current timestamp.
      operationId: "post-/conversations/v3/conversations/threads/{threadId}/messages"
      security:
      - private_apps:
        - conversations.write
      - oauth2:
        - conversations.write
      summary: Send a message to a thread.
      tags:
      - Conversations
  /conversations/v3/conversations/actors/batch/read:
    post:
      description: Resolve `ActorId`s to the underlying actors/participants.
      operationId: post-/conversations/v3/conversations/actors/batch/read
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get actors
      tags:
      - Conversations
  /conversations/v3/conversations/channel-accounts:
    get:
      operationId: get-/conversations/v3/conversations/channel-accounts
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get channel accounts.
      tags:
      - Conversations
  /conversations/v3/conversations/channels/{channelId}:
    get:
      operationId: "get-/conversations/v3/conversations/channels/{channelId}"
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get a single channel.
      tags:
      - Conversations
  /conversations/v3/conversations/threads/{threadId}/messages/{messageId}:
    get:
      operationId: "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}"
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get a single message.
      tags:
      - Conversations
  /conversations/v3/conversations/channels:
    get:
      operationId: get-/conversations/v3/conversations/channels
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get channels.
      tags:
      - Conversations
  /conversations/v3/conversations/actors/{actorId}:
    get:
      operationId: "get-/conversations/v3/conversations/actors/{actorId}"
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get a single actor.
      tags:
      - Conversations
  /conversations/v3/conversations/threads:
    get:
      operationId: get-/conversations/v3/conversations/threads
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get threads.
      tags:
      - Conversations
  /conversations/v3/conversations/channel-accounts/{channelAccountId}:
    get:
      operationId: "get-/conversations/v3/conversations/channel-accounts/{channelAccountId}"
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get a single channel account.
      tags:
      - Conversations
  /conversations/v3/conversations/inboxes/{inboxId}:
    get:
      operationId: "get-/conversations/v3/conversations/inboxes/{inboxId}"
      security:
      - oauth2:
        - conversations.read
      - private_apps:
        - conversations.read
      summary: Get a single conversations inbox.
      tags:
      - Conversations
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            conversations.read: Read from conversations
            conversations.write: Write to conversations
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
