openapi: 3.0.1
info:
  title: Campaigns Public Api
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: PROFESSIONAL
  x-hubspot-related-documentation:
  - name: Campaigns
    url: https://developers.hubspot.com/docs/guides/api/marketing/campaigns
  x-hubspot-introduction: "You can use campaign endpoints to create, read, update,\
    \ and delete marketing campaign data. For example, you can use these endpoints\
    \ to create and manage HubSpot campaigns from your external applications. You\
    \ can also transfer campaign data to external data warehouses for analytics."
servers:
- url: https://api.hubapi.com
tags:
- name: Basic
- name: Search
- name: Batch
- name: Reports
- name: Asset
- name: Budget
paths:
  /marketing/v3/campaigns/:
    get:
      description: "This endpoint allows users to search for and return a page of\
        \ campaigns based on various query parameters. Users can filter by name, sort,\
        \ and paginate through the campaigns, as well as control which properties\
        \ are returned in the response."
      operationId: get-/marketing/v3/campaigns/
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Campaign search
      tags:
      - Search
    post:
      description: "Create a campaign with the given properties and return the campaign\
        \ object, including the campaignGuid and created properties. "
      operationId: post-/marketing/v3/campaigns/
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Create a campaign
      tags:
      - Basic
  /marketing/v3/campaigns/batch/read:
    post:
      description: "This endpoint reads a batch of campaigns based on the provided\
        \ input data and returns the campaigns along with their associated assets.\
        \ \nThe maximum number of items in a batch request is 50.\nThe campaigns in\
        \ the response are not guaranteed to be in the same order as they were provided\
        \ in the request.\nIf duplicate campaign IDs are provided in the request,\
        \ duplicates will be ignored. The response will include only unique IDs and\
        \ will be returned without duplicates.\n"
      operationId: post-/marketing/v3/campaigns/batch/read
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Read a batch of campaigns
      tags:
      - Batch
  /marketing/v3/campaigns/batch/update:
    post:
      description: |-
        This endpoint updates a batch of campaigns based on the provided input data.
        The maximum number of items in a batch request is 50.
        If an empty string ("") is passed for any property in the Batch Update, it will reset that property's value.
      operationId: post-/marketing/v3/campaigns/batch/update
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Update a batch of campaigns
      tags:
      - Batch
  /marketing/v3/campaigns/{campaignGuid}/reports/metrics:
    get:
      description: "This endpoint retrieves key attribution metrics for a specified\
        \ campaign, such as sessions, new contacts, and influenced contacts."
      operationId: "get-/marketing/v3/campaigns/{campaignGuid}/reports/metrics"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: |
        Get Campaign Metrics
      tags:
      - Reports
  /marketing/v3/campaigns/{campaignGuid}/assets/{assetType}:
    get:
      description: |-
        This endpoint lists all assets of the campaign by asset type. The assetType parameter is required, and each request can only fetch assets of a single type.
        Asset metrics can also be fetched along with the assets; they are available only if start and end dates are provided.
      operationId: "get-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: List assets
      tags:
      - Asset
  /marketing/v3/campaigns/batch/archive:
    post:
      description: "This endpoint deletes a batch of campaigns. \nThe maximum number\
        \ of items in a batch request is 50.\nThe response will always be 204 No Content,\
        \ regardless of whether the campaigns exist or not, whether they were successfully\
        \ deleted or not, or if only some of the campaigns in the batch were deleted."
      operationId: post-/marketing/v3/campaigns/batch/archive
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Delete a batch of campaigns
      tags:
      - Batch
  /marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}:
    delete:
      description: |-
        Disassociate a specified asset from a campaign.
        Important: Currently, only the following asset types can be associated and disassociated via the API: Forms, Static lists, External website pages
      operationId: "delete-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Remove asset association
      tags:
      - Asset
    put:
      description: |-
        Associate a specified asset with a campaign.
        Important: Currently, only the following asset types can be associated and disassociated via the API: Forms, Static lists, External website pages
      operationId: "put-/marketing/v3/campaigns/{campaignGuid}/assets/{assetType}/{assetId}"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Add asset association
      tags:
      - Asset
  /marketing/v3/campaigns/{campaignGuid}/reports/revenue:
    get:
      description: |
        Fetch revenue attribution report data for a specified campaign
      operationId: "get-/marketing/v3/campaigns/{campaignGuid}/reports/revenue"
      security:
      - private_apps:
        - marketing.campaigns.revenue.read
      - oauth2:
        - marketing.campaigns.revenue.read
      summary: Fetch revenue
      tags:
      - Reports
  /marketing/v3/campaigns/batch/create:
    post:
      description: |-
        This endpoint creates a batch of campaigns. The maximum number of items in a batch request is 50.
        The campaigns in the response are not guaranteed to be in the same order as they were provided in the request.
      operationId: post-/marketing/v3/campaigns/batch/create
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Create a batch of campaigns
      tags:
      - Batch
  /marketing/v3/campaigns/{campaignGuid}/budget/totals:
    get:
      description: |-
        Retrieve detailed information about the budget and spend items for a specified campaign, including the total budget, total spend, and remaining budget.
        Budget and Spend items may be returned in any order, but the order field specifies their sequence based on the creation date. The item with order 0 is the oldest, and items with higher order values are newer
      operationId: "get-/marketing/v3/campaigns/{campaignGuid}/budget/totals"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Read budget
      tags:
      - Budget
  /marketing/v3/campaigns/{campaignGuid}:
    delete:
      description: |-
        Delete a specified campaign from the system.
        This call will return a 204 No Content response regardless of whether the campaignGuid provided corresponds to an existing campaign or not.
      operationId: "delete-/marketing/v3/campaigns/{campaignGuid}"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: 'Delete campaign '
      tags:
      - Basic
    get:
      description: "Get a campaign identified by a specific campaignGuid with the\
        \ given properties. Along with the campaign information, it also returns information\
        \ about assets. Depending on the query parameters used, this can also be used\
        \ to return information about the corresponding assets' metrics. Metrics are\
        \ available only if startDate and endDate are provided."
      operationId: "get-/marketing/v3/campaigns/{campaignGuid}"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Read a campaign
      tags:
      - Basic
    patch:
      description: |
        Perform a partial update of a campaign identified by the specified campaignGuid. Provided property values will be overwritten. Read-only and non-existent properties will cause 400 error.
        If an empty string is passed for any property in the Batch Update, it will reset that property's value.
      operationId: "patch-/marketing/v3/campaigns/{campaignGuid}"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Update campaign
      tags:
      - Basic
  /marketing/v3/campaigns/{campaignGuid}/reports/contacts/{contactType}:
    get:
      description: Fetch the list of contact IDs for the specified campaign and contact
        type
      operationId: "get-/marketing/v3/campaigns/{campaignGuid}/reports/contacts/{contactType}"
      security:
      - oauth2:
        - marketing.campaigns.read
      - private_apps:
        - marketing.campaigns.read
      summary: Fetch contact IDs
      tags:
      - Reports
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            marketing.campaigns.read: Read marketing campaigns
            marketing.campaigns.revenue.read: Read campaigns attribution revenue
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
