openapi: 3.0.1
info:
  description: All HubSpot objects store data in default and custom properties. These
    endpoints provide access to read and modify object properties in HubSpot.
  title: Properties
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: STARTER
  x-hubspot-api-use-case: Create a set of custom multi-select properties for storing
    contract data on company records.
  x-hubspot-related-documentation:
  - name: Properties guide
    url: https://developers.hubspot.com/docs/guides/api/crm/properties
  x-hubspot-introduction: "Use the properties API to store information in fields on\
    \ individual contact records. You can use this API to manage existing default\
    \ and custom properties, create new custom properties, and more."
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Groups
- name: Core
paths:
  /crm/v3/properties/{objectType}/batch/archive:
    post:
      description: "Archive a provided list of properties. This method will return\
        \ a 204 No Content response on success regardless of the initial state of\
        \ the property (e.g. active, already archived, non-existent)."
      operationId: "post-/crm/v3/properties/{objectType}/batch/archive_archive"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Archive a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}/groups/{groupName}:
    delete:
      description: "Move a property group identified by {groupName} to the recycling\
        \ bin."
      operationId: "delete-/crm/v3/properties/{objectType}/groups/{groupName}_archive"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Archive a property group
      tags:
      - Groups
    get:
      description: "Read a property group identified by {groupName}."
      operationId: "get-/crm/v3/properties/{objectType}/groups/{groupName}_getByName"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.orders.read
      - private_apps:
        - crm.objects.invoices.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read a property group
      tags:
      - Groups
    patch:
      description: "Perform a partial update of a property group identified by {groupName}.\
        \ Provided fields will be overwritten."
      operationId: "patch-/crm/v3/properties/{objectType}/groups/{groupName}_update"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Update a property group
      tags:
      - Groups
  /crm/v3/properties/{objectType}/{propertyName}:
    delete:
      description: "Move a property identified by {propertyName} to the recycling\
        \ bin."
      operationId: "delete-/crm/v3/properties/{objectType}/{propertyName}_archive"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Archive a property
      tags:
      - Core
    get:
      description: "Read a property identified by {propertyName}."
      operationId: "get-/crm/v3/properties/{objectType}/{propertyName}_getByName"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.orders.read
      - private_apps:
        - crm.objects.invoices.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read a property
      tags:
      - Core
    patch:
      description: "Perform a partial update of a property identified by {propertyName}.\
        \ Provided fields will be overwritten."
      operationId: "patch-/crm/v3/properties/{objectType}/{propertyName}_update"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Update a property
      tags:
      - Core
  /crm/v3/properties/{objectType}/batch/read:
    post:
      description: Read a provided list of properties.
      operationId: "post-/crm/v3/properties/{objectType}/batch/read_read"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.orders.read
      - private_apps:
        - crm.objects.invoices.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}/batch/create:
    post:
      description: Create a batch of properties using the same rules as when creating
        an individual property.
      operationId: "post-/crm/v3/properties/{objectType}/batch/create_create"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}:
    get:
      description: Read all existing properties for the specified object type and
        HubSpot account.
      operationId: "get-/crm/v3/properties/{objectType}_getAll"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.orders.read
      - private_apps:
        - crm.objects.invoices.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read all properties
      tags:
      - Core
    post:
      description: Create and return a copy of a new property for the specified object
        type.
      operationId: "post-/crm/v3/properties/{objectType}_create"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a property
      tags:
      - Core
  /crm/v3/properties/{objectType}/groups:
    get:
      description: Read all existing property groups for the specified object type
        and HubSpot account.
      operationId: "get-/crm/v3/properties/{objectType}/groups_getAll"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.schemas.listings.read
      - private_apps:
        - crm.schemas.listings.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.sensitive.write
      - oauth2:
        - crm.schemas.carts.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - automation
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.sensitive.read.v2
      - private_apps:
        - crm.schemas.services.read
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.invoices.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.schemas.subscriptions.read
      - private_apps:
        - crm.schemas.companies.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.write
      - private_apps:
        - crm.objects.deals.sensitive.read
      - private_apps:
        - crm.objects.appointments.sensitive.write
      - oauth2:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.companies.highly_sensitive.write
      - private_apps:
        - tickets.sensitive
      - private_apps:
        - crm.objects.feedback_submissions.read
      - oauth2:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.custom.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.appointments.sensitive.read
      - private_apps:
        - crm.objects.companies.sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.custom.highly_sensitive.read
      - oauth2:
        - crm.schemas.courses.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.objects.leads.write
      - private_apps:
        - crm.schemas.contacts.read
      - private_apps:
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.marketing_events.write
      - private_apps:
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.schemas.commercepayments.read
      - oauth2:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.schemas.custom.read
      - private_apps:
        - media_bridge.read
      - oauth2:
        - crm.schemas.commercepayments.read
      - private_apps:
        - timeline
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.read.v2
      - private_apps:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.custom.sensitive.write
      - private_apps:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.contacts.sensitive.read
      - private_apps:
        - crm.schemas.invoices.read
      - private_apps:
        - crm.objects.marketing_events.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.quotes.read
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - private_apps:
        - crm.objects.appointments.write
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.owners.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - automation
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.companies.sensitive.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.objects.custom.sensitive.write.v2
      - private_apps:
        - crm.schemas.carts.read
      - oauth2:
        - crm.schemas.services.read
      - private_apps:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - private_apps:
        - crm.objects.deals.highly_sensitive.read
      - oauth2:
        - crm.schemas.subscriptions.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - private_apps:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.feedback_submissions.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - e-commerce
      - private_apps:
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.orders.read
      - private_apps:
        - crm.objects.invoices.read
      - oauth2:
        - crm.schemas.deals.read
      - private_apps:
        - crm.schemas.appointments.read
      - oauth2:
        - crm.schemas.orders.read
      - private_apps:
        - crm.schemas.courses.read
      - private_apps:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - private_apps:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - private_apps:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.custom.sensitive.read
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - timeline
      - oauth2:
        - crm.pipelines.orders.read
      - oauth2:
        - crm.schemas.invoices.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.services.read
      - private_apps:
        - crm.objects.deals.highly_sensitive.write
      - oauth2:
        - crm.objects.marketing_events.read
      summary: Read all property groups
      tags:
      - Groups
    post:
      description: Create and return a copy of a new property group.
      operationId: "post-/crm/v3/properties/{objectType}/groups_create"
      security:
      - private_apps:
        - crm.schemas.invoices.write
      - private_apps:
        - tickets
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.invoices.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - private_apps:
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - tickets
      - private_apps:
        - tickets.sensitive.v2
      - private_apps:
        - e-commerce
      - oauth2:
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.appointments.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.schemas.appointments.write
      - oauth2:
        - crm.schemas.courses.write
      - private_apps:
        - crm.schemas.courses.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.carts.write
      - private_apps:
        - crm.pipelines.orders.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - private_apps:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.schemas.services.write
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.services.write
      - oauth2:
        - crm.objects.users.write
      - private_apps:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - tickets.highly_sensitive
      - private_apps:
        - crm.schemas.listings.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2:
        - crm.schemas.subscriptions.write
      - oauth2:
        - crm.schemas.listings.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a property group
      tags:
      - Groups
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.marketing_events.write: Write marketing events
            crm.objects.users.read: Read User CRM objects
            crm.objects.deals.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.marketing_events.read: Read marketing events
            crm.objects.companies.read: ' '
            crm.objects.custom.write: Change custom object records
            tickets: Read and write tickets
            crm.objects.goals.write: Write goals
            crm.objects.custom.read: View custom object records
            crm.schemas.subscriptions.read: Read subscriptions schema
            crm.schemas.orders.read: Read order property settings
            crm.objects.services.read: Read services
            crm.objects.orders.read: Read Orders
            crm.schemas.appointments.read: Read appointments property settings
            crm.objects.companies.sensitive.read.v2: ' '
            crm.schemas.custom.read: View custom object definitions
            crm.schemas.deals.read: ' '
            crm.pipelines.orders.read: View details about your cart pipelines including
              pipeline stage information
            crm.objects.listings.read: Read listings
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.objects.owners.read: ' '
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
            crm.schemas.courses.read: Read courses property settings
            crm.objects.companies.highly_sensitive.read.v2: View company records (highly-sensitive)
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.schemas.services.read: Read services property settings
            crm.objects.carts.read: Read carts
            crm.objects.contacts.write: ' '
            crm.objects.leads.write: Modify lead objects
            crm.schemas.listings.read: Read listings property settings
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.custom.sensitive.write.v2: Change custom object records (sensitive)
            crm.objects.appointments.read: Read appointments
            crm.objects.goals.read: Read goals
            crm.schemas.carts.read: Read cart property settings
            crm.objects.services.write: Write services
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.contacts.read: ' '
            crm.objects.custom.sensitive.read.v2: View custom object records (sensitive)
            crm.objects.appointments.sensitive.read.v2: Read appointments (sensitive)
            crm.objects.leads.read: Read lead objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.appointments.write: Write appointments
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            crm.schemas.contacts.read: ' '
            automation: Read from and write to my Workflows
            crm.objects.courses.write: Write courses
            crm.objects.quotes.write: Quotes
            crm.objects.invoices.read: Read invoices objects
            crm.objects.feedback_submissions.read: View feedback survey submissions
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.schemas.commercepayments.read: Read the COMMERCE_PAYMENT properties.
            crm.objects.listings.write: Write listings
            crm.schemas.line_items.read: Line Items schemas
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.deals.highly_sensitive.read.v2: View deal records (highly-sensitive)
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.line_items.write: Line Items
            crm.schemas.invoices.read: Read invoices schema
            crm.objects.deals.sensitive.read.v2: ' '
            crm.objects.deals.write: ' '
            crm.objects.custom.highly_sensitive.read.v2: View custom object records
              (highly-sensitive)
            crm.objects.custom.highly_sensitive.write.v2: Change custom object records
              (highly-sensitive)
            crm.objects.subscriptions.write: Write to Commerce Subscriptions
            media_bridge.read: Read media and media events
            e-commerce: e-commerce
            crm.schemas.companies.read: ' '
            crm.schemas.quotes.read: Quotes schemas
            timeline: Create timeline events
            crm.objects.quotes.read: Quotes
            crm.objects.line_items.read: Line Items
            crm.objects.companies.sensitive.write.v2: ' '
            crm.objects.invoices.write: Write invoices
            crm.schemas.subscriptions.write: Write to Subscription properties
            crm.objects.users.write: Write User CRM objects
            crm.objects.orders.write: Write orders
            crm.schemas.contacts.write: ' '
            crm.schemas.appointments.write: Write appointments property settings
            crm.schemas.companies.write: ' '
            crm.schemas.courses.write: Write courses property settings
            crm.pipelines.orders.write: "Create, delete, or make to your order pipelines\
              \ or their respective stages"
            crm.schemas.services.write: Write services property settings
            crm.schemas.listings.write: Write listings property settings
            crm.schemas.deals.write: ' '
            crm.schemas.carts.write: Write cart property settings
            crm.objects.carts.write: Write cart
            crm.schemas.invoices.write: Write invoices schema
            crm.schemas.orders.write: Write order property settings
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: STARTER
