openapi: 3.0.1
info:
  title: Conversations Custom Channels
  version: v3
  x-hubspot-product-tier-requirements:
    sales: ENTERPRISE
    service: ENTERPRISE
  x-hubspot-api-use-case: "Allow admins to install an integration with a third-party\
    \ messaging channel that your team uses to communicate with customers, to allow\
    \ users in your account to manage their conversations for that channel directly\
    \ in HubSpot."
  x-hubspot-related-documentation:
  - name: Custom Channels Guide
    url: https://developers.hubspot.com/docs/guides/api/conversations/create-custom-channels
  x-hubspot-introduction: 'Use the custom channels API to create custom channels to
    build a bridge between an external message service and HubSpot''s inbox or help
    desk features. '
servers:
- url: https://api.hubapi.com
tags:
- name: Channels
- name: Messages
- name: Channel Account Staging Tokens
- name: Channel Accounts
paths:
  /conversations/v3/custom-channels/{channelId}:
    delete:
      description: Use this API to archive a registered custom channel
      operationId: "delete-/conversations/v3/custom-channels/{channelId}"
      security:
      - developer_hapikey: []
      summary: Archive a custom channel
      tags:
      - Channels
    get:
      description: Retrieve the details about a custom channel. This API allows you
        to see a custom channel's current capabilties and other configuration metadata
      operationId: "get-/conversations/v3/custom-channels/{channelId}"
      security:
      - developer_hapikey: []
      summary: Get a custom channel
      tags:
      - Channels
    patch:
      description: This endpoint can be used to update a channel's capabilities. You
        can also use it to update the channel's webhookUri and its channelAccountConnectionRedirectUrl.
      operationId: "patch-/conversations/v3/custom-channels/{channelId}"
      security:
      - developer_hapikey: []
      summary: Update a custom channel
      tags:
      - Channels
  /conversations/v3/custom-channels/{channelId}/messages/{messageId}:
    get:
      description: Get the PublicConversationsMessage that represents a message sent
        over a custom channel
      operationId: "get-/conversations/v3/custom-channels/{channelId}/messages/{messageId}"
      security:
      - oauth2:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.read
      summary: Get a message
      tags:
      - Messages
    patch:
      description: "Use this API to update a message's status to indicate if it was\
        \ successfully sent, failed to send, or was read"
      operationId: "patch-/conversations/v3/custom-channels/{channelId}/messages/{messageId}"
      security:
      - private_apps:
        - conversations.custom_channels.write
      - oauth2:
        - conversations.custom_channels.write
      summary: 'Update message '
      tags:
      - Messages
  /conversations/v3/custom-channels/{channelId}/channel-account-staging-tokens/{accountToken}:
    patch:
      description: This API is used for integrators creating public apps. Use this
        API to update a channel account staging token's account name and delivery
        identifier. This information will be applied to the channel account created
        from this staging token.
      operationId: "patch-/conversations/v3/custom-channels/{channelId}/channel-account-staging-tokens/{accountToken}"
      security:
      - oauth2:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.write
      - oauth2:
        - conversations.custom_channels.write
      summary: Update a channel account staging token
      tags:
      - Channel Account Staging Tokens
  /conversations/v3/custom-channels/{channelId}/channel-accounts:
    get:
      operationId: "get-/conversations/v3/custom-channels/{channelId}/channel-accounts"
      security:
      - oauth2:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.write
      - oauth2:
        - conversations.custom_channels.write
      summary: Query channel accounts
      tags:
      - Channel Accounts
    post:
      description: This API allows you to create one or more accounts that all talk
        over a single channel but using different delivery identifiers.
      operationId: "post-/conversations/v3/custom-channels/{channelId}/channel-accounts"
      security:
      - oauth2:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.write
      - oauth2:
        - conversations.custom_channels.write
      summary: Create a channel account
      tags:
      - Channel Accounts
  /conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}:
    get:
      description: "Retrieve a PublicChannelAccount that contains all the metadata\
        \ about your channel account. This includes information like its channel,\
        \ associated inbox id, and delivery identifier information."
      operationId: "get-/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}"
      security:
      - oauth2:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.write
      - oauth2:
        - conversations.custom_channels.write
      summary: Get a channel account by id
      tags:
      - Channel Accounts
    patch:
      description: This API is used to update the name of the channel account and
        it's isAuthorized status. Setting to isAuthorized flag to False disables the
        channel account.
      operationId: "patch-/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}"
      security:
      - oauth2:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.read
      - private_apps:
        - conversations.custom_channels.write
      - oauth2:
        - conversations.custom_channels.write
      summary: Update a channel account
      tags:
      - Channel Accounts
  /conversations/v3/custom-channels/:
    get:
      operationId: get-/conversations/v3/custom-channels/
      security:
      - developer_hapikey: []
      summary: Get all channels for app
      tags:
      - Channels
    post:
      description: Register a new channel along with its capabilities and the webhook
        url that will be used to receive messages published over the channel
      operationId: post-/conversations/v3/custom-channels/
      security:
      - developer_hapikey: []
      summary: Create a custom channel
      tags:
      - Channels
  /conversations/v3/custom-channels/{channelId}/messages:
    post:
      description: Publish a message over your custom channel
      operationId: "post-/conversations/v3/custom-channels/{channelId}/messages"
      security:
      - private_apps:
        - conversations.custom_channels.write
      - oauth2:
        - conversations.custom_channels.write
      summary: Publish a message
      tags:
      - Messages
components:
  securitySchemes:
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            conversations.custom_channels.read: Read messages and manage Channel Accounts
              for an included Custom Channel.
            conversations.custom_channels.write: Publish messages into HubSpot and
              manage Channel Accounts for an included Custom Channel.
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
