openapi: 3.0.1
info:
  description: ""
  title: Commerce Payments
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-api-use-case: Fetch all refunded payments in the account.
  x-hubspot-related-documentation:
  - name: Payments Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/commerce/payments
  x-hubspot-introduction: "Use the payments API to fetch information about an account's\
    \ payments. This is a read-only API, so it cannot be used for creating new or\
    \ managing existing payments.\_Note that the account must be set up to collect\
    \ payments through either HubSpot payments or Stripe payment processing."
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Basic
- name: Search
paths:
  /crm/v3/objects/commerce_payments/batch/read:
    post:
      description: 'Retrieve a batch of payments by ID (`commercePaymentId`) or unique
        property value (`idProperty`). '
      operationId: post-/crm/v3/objects/commerce_payments/batch/read
      security:
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      summary: Retrieve a batch of payments
      tags:
      - Batch
  /crm/v3/objects/commerce_payments/{commercePaymentId}:
    get:
      description: "Read an Object identified by `{commercePaymentId}`. `{commercePaymentId}`\
        \ refers to the internal object ID by default, or optionally any unique property\
        \ value as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: "get-/crm/v3/objects/commerce_payments/{commercePaymentId}"
      security:
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      summary: Read
      tags:
      - Basic
  /crm/v3/objects/commerce_payments:
    get:
      description: "Retrieve all payments, using query parameters to specify the information\
        \ that gets returned."
      operationId: get-/crm/v3/objects/commerce_payments
      security:
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      summary: Retrieve payments
      tags:
      - Basic
  /crm/v3/objects/commerce_payments/search:
    post:
      description: "Search for payments by filtering on properties, searching through\
        \ associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request)."
      operationId: post-/crm/v3/objects/commerce_payments/search
      security:
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      summary: Search for payments
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.users.write: Write User CRM objects
            crm.objects.services.write: Write services
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.custom.write: Change custom object records
            crm.objects.quotes.read: Quotes
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.custom.highly_sensitive.read.v2: View custom object records
              (highly-sensitive)
            crm.objects.goals.write: Write goals
            crm.objects.custom.sensitive.read.v2: View custom object records (sensitive)
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.appointments.sensitive.read.v2: Read appointments (sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.deals.write: ' '
            crm.objects.leads.write: Modify lead objects
            crm.objects.companies.read: ' '
            crm.objects.listings.read: Read listings
            crm.objects.deals.highly_sensitive.read.v2: View deal records (highly-sensitive)
            crm.objects.contacts.write: ' '
            crm.objects.carts.write: Write cart
            crm.objects.companies.sensitive.read.v2: ' '
            crm.objects.invoices.read: Read invoices objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.invoices.write: Write invoices
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            crm.objects.goals.read: Read goals
            crm.objects.custom.highly_sensitive.write.v2: Change custom object records
              (highly-sensitive)
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.appointments.write: Write appointments
            media_bridge.read: Read media and media events
            crm.objects.line_items.write: Line Items
            crm.objects.orders.read: Read Orders
            crm.objects.subscriptions.write: Write to Commerce Subscriptions
            crm.objects.contacts.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.quotes.write: Quotes
            crm.objects.deals.sensitive.read.v2: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.users.read: Read User CRM objects
            tickets: Read and write tickets
            crm.objects.companies.sensitive.write.v2: ' '
            crm.objects.leads.read: Read lead objects
            crm.objects.services.read: Read services
            crm.objects.courses.write: Write courses
            crm.objects.custom.read: View custom object records
            crm.objects.listings.write: Write listings
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.deals.read: ' '
            crm.objects.companies.highly_sensitive.read.v2: View company records (highly-sensitive)
            e-commerce: e-commerce
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.objects.appointments.read: Read appointments
            crm.objects.orders.write: Write orders
            crm.objects.custom.sensitive.write.v2: Change custom object records (sensitive)
            crm.objects.carts.read: Read carts
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
