openapi: 3.0.1
info:
  title: Settings Multicurrency
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-api-use-case: "If your company conducts business in different countries,\
    \ use this API to adjust your account's currency settings based on requirements\
    \ or data from a third-party provider."
  x-hubspot-related-documentation:
  - name: Currencies guide
    url: https://developers.hubspot.com/docs/guides/api/settings/currencies
  x-hubspot-introduction: "Use the currencies API to manage the currency settings\
    \ in your HubSpot account, including your company's primary currency, any additional\
    \ currencies, and updating exchange rates."
servers:
- url: https://api.hubapi.com
tags:
- name: Currency
paths:
  /settings/v3/currencies/exchange-rates:
    get:
      operationId: get-/settings/v3/currencies/exchange-rates
      security:
      - private_apps:
        - settings.currencies.read
      - oauth2:
        - settings.currencies.read
      tags:
      - Currency
    post:
      operationId: post-/settings/v3/currencies/exchange-rates
      security:
      - private_apps:
        - settings.currencies.write
      - oauth2:
        - settings.currencies.write
      tags:
      - Currency
  /settings/v3/currencies/codes:
    get:
      operationId: get-/settings/v3/currencies/codes
      security:
      - private_apps:
        - settings.currencies.read
      - oauth2:
        - settings.currencies.read
      tags:
      - Currency
  /settings/v3/currencies/company-currency:
    get:
      operationId: get-/settings/v3/currencies/company-currency
      security:
      - private_apps:
        - settings.currencies.read
      - oauth2:
        - settings.currencies.read
      tags:
      - Currency
    put:
      operationId: put-/settings/v3/currencies/company-currency
      security:
      - private_apps:
        - settings.currencies.write
      - oauth2:
        - settings.currencies.write
      tags:
      - Currency
  /settings/v3/currencies/exchange-rates/batch/update:
    post:
      operationId: post-/settings/v3/currencies/exchange-rates/batch/update
      security:
      - private_apps:
        - settings.currencies.write
      - oauth2:
        - settings.currencies.write
      tags:
      - Currency
  /settings/v3/currencies/exchange-rates/current:
    get:
      operationId: get-/settings/v3/currencies/exchange-rates/current
      security:
      - private_apps:
        - settings.currencies.read
      - oauth2:
        - settings.currencies.read
      tags:
      - Currency
  /settings/v3/currencies/exchange-rates/update-visibility:
    post:
      operationId: post-/settings/v3/currencies/exchange-rates/update-visibility
      security:
      - private_apps:
        - settings.currencies.write
      - oauth2:
        - settings.currencies.write
      tags:
      - Currency
  /settings/v3/currencies/exchange-rates/{exchangeRateId}:
    get:
      operationId: "get-/settings/v3/currencies/exchange-rates/{exchangeRateId}"
      security:
      - private_apps:
        - settings.currencies.read
      - oauth2:
        - settings.currencies.read
      tags:
      - Currency
    patch:
      operationId: "patch-/settings/v3/currencies/exchange-rates/{exchangeRateId}"
      security:
      - private_apps:
        - settings.currencies.write
      - oauth2:
        - settings.currencies.write
      tags:
      - Currency
  /settings/v3/currencies/exchange-rates/batch/create:
    post:
      operationId: post-/settings/v3/currencies/exchange-rates/batch/create
      security:
      - private_apps:
        - settings.currencies.write
      - oauth2:
        - settings.currencies.write
      tags:
      - Currency
  /settings/v3/currencies/exchange-rates/batch/read:
    post:
      operationId: post-/settings/v3/currencies/exchange-rates/batch/read
      security:
      - private_apps:
        - settings.currencies.read
      - oauth2:
        - settings.currencies.read
      tags:
      - Currency
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            settings.currencies.read: Read currency and exchange rate data.
            settings.currencies.write: Write currency and exchange rate data.
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
